language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules

install:
  - npm install

script:
  - npm run test

after_script:
  - npm run cover  

notifications:
  webhooks: https://app.fossa.io/hooks/travisci  