language: node_js

node_js:
  - 8

cache:
  directories:
    - node_modules
before_script:
    - npm install -g license-cli
    - license-cli auth ${FOSSA_API_TOKEN}
    - license-cli scan -r $TRAVIS_COMMIT
install:
  - npm install

script:
  - npm run test

after_script:
  - npm run cover  